# Generated by Django 3.1.1 on 2020-10-30 10:20

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='upload/img/currency/', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currency',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='upload/img/pay/', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='upload/img/soft/', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Softwares',
            },
        ),
        migrations.CreateModel(
            name='Casino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('name', models.CharField(max_length=50, verbose_name='Title')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('link', models.CharField(max_length=180, null=True, verbose_name='Link')),
                ('trust_score', models.CharField(choices=[('50', '5.0'), ('49', '4.9'), ('48', '4.8'), ('47', '4.7'), ('46', '4.6'), ('45', '4.5'), ('44', '4.4'), ('43', '4.3'), ('42', '4.2'), ('41', '4.1'), ('40', '4.0'), ('35', '3.5'), ('30', '3.0'), ('25', '2.5'), ('20', '2.0'), ('15', '1.5'), ('10', '1.0'), ('0', '0.0')], max_length=3, verbose_name='Trust & Fairness Score')),
                ('games_score', models.CharField(choices=[('50', '5.0'), ('49', '4.9'), ('48', '4.8'), ('47', '4.7'), ('46', '4.6'), ('45', '4.5'), ('44', '4.4'), ('43', '4.3'), ('42', '4.2'), ('41', '4.1'), ('40', '4.0'), ('35', '3.5'), ('30', '3.0'), ('25', '2.5'), ('20', '2.0'), ('15', '1.5'), ('10', '1.0'), ('0', '0.0')], max_length=3, verbose_name='Games & Software Score')),
                ('bonus_score', models.CharField(choices=[('50', '5.0'), ('49', '4.9'), ('48', '4.8'), ('47', '4.7'), ('46', '4.6'), ('45', '4.5'), ('44', '4.4'), ('43', '4.3'), ('42', '4.2'), ('41', '4.1'), ('40', '4.0'), ('35', '3.5'), ('30', '3.0'), ('25', '2.5'), ('20', '2.0'), ('15', '1.5'), ('10', '1.0'), ('0', '0.0')], max_length=3, verbose_name='Bonuses & Promo Score')),
                ('support_score', models.CharField(choices=[('50', '5.0'), ('49', '4.9'), ('48', '4.8'), ('47', '4.7'), ('46', '4.6'), ('45', '4.5'), ('44', '4.4'), ('43', '4.3'), ('42', '4.2'), ('41', '4.1'), ('40', '4.0'), ('35', '3.5'), ('30', '3.0'), ('25', '2.5'), ('20', '2.0'), ('15', '1.5'), ('10', '1.0'), ('0', '0.0')], max_length=3, verbose_name='Customer Support Score')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(upload_to='upload/img/logos/', verbose_name='Casino Logo')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='upload/img/gifs/', verbose_name='Gif Image')),
                ('description', models.CharField(max_length=80, verbose_name='Short description')),
                ('description_trans', models.CharField(max_length=80, verbose_name='Short description translate')),
                ('bonus', models.IntegerField(verbose_name='Welcome bonus')),
                ('limit', models.IntegerField(null=True, verbose_name='Bonus limit')),
                ('mobile', models.BooleanField(blank=True, null=True, verbose_name='Mobile')),
                ('live', models.BooleanField(blank=True, null=True, verbose_name='Live chat')),
                ('fun', models.BooleanField(blank=True, null=True, verbose_name='Free games')),
                ('adv1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1')),
                ('adv2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2')),
                ('adv3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3')),
                ('adv4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4')),
                ('ankor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Anchor')),
                ('review', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Review')),
                ('games', models.IntegerField(blank=True, null=True, verbose_name='Games count')),
                ('currency', models.ManyToManyField(to='casinos.Currency')),
                ('pay', models.ManyToManyField(related_name='pays', to='casinos.Payment')),
                ('soft', models.ManyToManyField(to='casinos.Software')),
                ('withdraw', models.ManyToManyField(related_name='payout', to='casinos.Payment')),
            ],
            options={
                'verbose_name': 'Casino',
                'verbose_name_plural': 'Casinos',
                'ordering': ['-trust_score', '-games_score', '-bonus_score', '-support_score'],
            },
        ),
    ]
