# Generated by Django 3.1.1 on 2020-10-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='logo_color',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Logo color'),
        ),
    ]
