# Generated by Django 3.1.1 on 2020-11-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0005_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='menu_name',
            field=models.CharField(default=0, max_length=50, verbose_name='menu'),
            preserve_default=False,
        ),
    ]
