# Generated by Django 3.1.1 on 2020-11-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0006_country_menu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='fb',
            field=models.URLField(blank=True, null=True, verbose_name='FaceBook'),
        ),
        migrations.AddField(
            model_name='casino',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='casino',
            name='license',
            field=models.URLField(blank=True, null=True, verbose_name='License'),
        ),
        migrations.AddField(
            model_name='casino',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='casino',
            name='winner',
            field=models.URLField(blank=True, null=True, verbose_name='WinLink'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='link',
            field=models.URLField(verbose_name='Link'),
        ),
    ]
