# Generated by Django 3.1.1 on 2020-11-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0007_auto_20201111_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='license',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='License'),
        ),
    ]
