# Generated by Django 3.1.1 on 2020-11-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0009_casino_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino',
            name='description',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='description_trans',
        ),
    ]
