# Generated by Django 3.1.1 on 2020-11-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0010_auto_20201113_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='adv1_au',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_de',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_fi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_hu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_nl',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_pl',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_sv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_au',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_de',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_fi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_hu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_nl',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_pl',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_sv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_au',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_de',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_fi',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_hu',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_it',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_nl',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_pl',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_sv',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
    ]
