# Generated by Django 3.1.1 on 2020-11-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0011_auto_20201113_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino',
            name='name_au',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_fi',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_hu',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_it',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_nl',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_pl',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_sv',
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_au',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_de',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_fi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_hu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_nl',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_pl',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_sv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3'),
        ),
    ]
