# Generated by Django 3.1.1 on 2020-11-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0013_auto_20201113_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='adv1_au',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_au',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_au',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3'),
        ),
    ]
