# Generated by Django 3.1.1 on 2020-11-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0014_auto_20201113_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='menu_name_au',
            field=models.CharField(max_length=50, null=True, verbose_name='menu'),
        ),
        migrations.AddField(
            model_name='country',
            name='menu_name_de',
            field=models.CharField(max_length=50, null=True, verbose_name='menu'),
        ),
        migrations.AddField(
            model_name='country',
            name='menu_name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='menu'),
        ),
        migrations.AddField(
            model_name='country',
            name='menu_name_fi',
            field=models.CharField(max_length=50, null=True, verbose_name='menu'),
        ),
        migrations.AddField(
            model_name='country',
            name='menu_name_hu',
            field=models.CharField(max_length=50, null=True, verbose_name='menu'),
        ),
        migrations.AddField(
            model_name='country',
            name='menu_name_it',
            field=models.CharField(max_length=50, null=True, verbose_name='menu'),
        ),
        migrations.AddField(
            model_name='country',
            name='menu_name_nl',
            field=models.CharField(max_length=50, null=True, verbose_name='menu'),
        ),
        migrations.AddField(
            model_name='country',
            name='menu_name_pl',
            field=models.CharField(max_length=50, null=True, verbose_name='menu'),
        ),
        migrations.AddField(
            model_name='country',
            name='menu_name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='menu'),
        ),
        migrations.AddField(
            model_name='country',
            name='menu_name_sv',
            field=models.CharField(max_length=50, null=True, verbose_name='menu'),
        ),
    ]
