# Generated by Django 3.1.1 on 2020-11-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0015_auto_20201113_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casino',
            options={'ordering': ['-position'], 'verbose_name': 'Casino', 'verbose_name_plural': 'Casinos'},
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv1',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv1_au',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv1_de',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv1_en',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv1_fi',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv1_hu',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv1_it',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv1_nl',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv1_pl',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv1_ru',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv1_sv',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv2',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv2_au',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv2_de',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv2_en',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv2_fi',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv2_hu',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv2_it',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv2_nl',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv2_pl',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv2_ru',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv2_sv',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv3',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv3_au',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv3_de',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv3_en',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv3_fi',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv3_hu',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv3_it',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv3_nl',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv3_pl',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv3_ru',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv3_sv',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv4',
        ),
        migrations.AddField(
            model_name='casino',
            name='badge',
            field=models.CharField(choices=[('new', 'Newest'), ('best', 'Best'), ('win', 'Winner')], default=0, max_length=8, verbose_name='Badge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casino',
            name='position_au',
            field=models.IntegerField(null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='casino',
            name='position_de',
            field=models.IntegerField(null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='casino',
            name='position_en',
            field=models.IntegerField(null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='casino',
            name='position_fi',
            field=models.IntegerField(null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='casino',
            name='position_hu',
            field=models.IntegerField(null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='casino',
            name='position_it',
            field=models.IntegerField(null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='casino',
            name='position_nl',
            field=models.IntegerField(null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='casino',
            name='position_pl',
            field=models.IntegerField(null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='casino',
            name='position_ru',
            field=models.IntegerField(null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='casino',
            name='position_sv',
            field=models.IntegerField(null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='casino',
            name='review_au',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='casino',
            name='review_de',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='casino',
            name='review_en',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='casino',
            name='review_fi',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='casino',
            name='review_hu',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='casino',
            name='review_it',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='casino',
            name='review_nl',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='casino',
            name='review_pl',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='casino',
            name='review_ru',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='casino',
            name='review_sv',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='casino',
            name='seo_description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='casino',
            name='seo_description_au',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='casino',
            name='seo_description_de',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='casino',
            name='seo_description_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='casino',
            name='seo_description_fi',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='casino',
            name='seo_description_hu',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='casino',
            name='seo_description_it',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='casino',
            name='seo_description_nl',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='casino',
            name='seo_description_pl',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='casino',
            name='seo_description_ru',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='casino',
            name='seo_description_sv',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='casino',
            name='seo_title',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='seo_title_au',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='seo_title_de',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='seo_title_en',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='seo_title_fi',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='seo_title_hu',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='seo_title_it',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='seo_title_nl',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='seo_title_pl',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='seo_title_ru',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='seo_title_sv',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_description_au',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_description_de',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_description_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_description_fi',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_description_hu',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_description_it',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_description_nl',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_description_pl',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_description_ru',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_description_sv',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_title',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_title_au',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_title_de',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_title_en',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_title_fi',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_title_hu',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_title_it',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_title_nl',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_title_pl',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_title_ru',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_title_sv',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='country',
            name='text',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Page text'),
        ),
        migrations.AddField(
            model_name='country',
            name='text_au',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Page text'),
        ),
        migrations.AddField(
            model_name='country',
            name='text_de',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Page text'),
        ),
        migrations.AddField(
            model_name='country',
            name='text_en',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Page text'),
        ),
        migrations.AddField(
            model_name='country',
            name='text_fi',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Page text'),
        ),
        migrations.AddField(
            model_name='country',
            name='text_hu',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Page text'),
        ),
        migrations.AddField(
            model_name='country',
            name='text_it',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Page text'),
        ),
        migrations.AddField(
            model_name='country',
            name='text_nl',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Page text'),
        ),
        migrations.AddField(
            model_name='country',
            name='text_pl',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Page text'),
        ),
        migrations.AddField(
            model_name='country',
            name='text_ru',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Page text'),
        ),
        migrations.AddField(
            model_name='country',
            name='text_sv',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Page text'),
        ),
        migrations.AddField(
            model_name='currency',
            name='seo_description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='currency',
            name='seo_title',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='payment',
            name='seo_description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='payment',
            name='seo_title',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='software',
            name='seo_description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='software',
            name='seo_title',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title'),
        ),
    ]
