# Generated by Django 3.1.1 on 2020-11-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0016_auto_20201116_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='badge',
            field=models.CharField(blank=True, choices=[('new', 'Newest'), ('best', 'Best'), ('win', 'Winner')], max_length=8, null=True, verbose_name='Badge'),
        ),
    ]
