# Generated by Django 3.1.1 on 2020-11-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0017_auto_20201116_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casino',
            options={'ordering': ['position'], 'verbose_name': 'Casino', 'verbose_name_plural': 'Casinos'},
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_au',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_de',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_en',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_fi',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_hu',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_it',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_nl',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_pl',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_ru',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_sv',
        ),
    ]
