# Generated by Django 3.1.1 on 2020-11-17 10:15

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0018_auto_20201116_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='upload/img/pay/', verbose_name='logo')),
                ('seo_title', models.TextField(blank=True, max_length=80, null=True, verbose_name='SEO Title')),
                ('seo_description', models.TextField(blank=True, max_length=200, null=True, verbose_name='SEO Description')),
            ],
            options={
                'verbose_name': 'Games',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.AddField(
            model_name='casino',
            name='games_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Games count'),
        ),
        migrations.RemoveField(
            model_name='casino',
            name='games',
        ),
        migrations.AddField(
            model_name='casino',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='games', to='casinos.Games'),
        ),
    ]
