# Generated by Django 3.1.1 on 2020-12-22 12:56

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0025_auto_20201222_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='upload/img/flags/page/', verbose_name='flag for page'),
        ),
    ]
