# Generated by Django 3.1.1 on 2020-12-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0026_auto_20201222_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
    ]
