# Generated by Django 3.1.1 on 2020-12-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0027_auto_20201222_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='top_text',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Top page text'),
        ),
    ]
