# Generated by Django 3.1.1 on 2020-12-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0028_country_top_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='adj_name_au',
            field=models.CharField(max_length=50, null=True, verbose_name='adjective name'),
        ),
        migrations.AddField(
            model_name='country',
            name='adj_name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='adjective name'),
        ),
        migrations.AddField(
            model_name='country',
            name='adj_name_fi',
            field=models.CharField(max_length=50, null=True, verbose_name='adjective name'),
        ),
        migrations.AddField(
            model_name='country',
            name='adj_name_sv',
            field=models.CharField(max_length=50, null=True, verbose_name='adjective name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_au',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_fi',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_sv',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='country',
            name='top_text_au',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Top page text'),
        ),
        migrations.AddField(
            model_name='country',
            name='top_text_en',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Top page text'),
        ),
        migrations.AddField(
            model_name='country',
            name='top_text_fi',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Top page text'),
        ),
        migrations.AddField(
            model_name='country',
            name='top_text_sv',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Top page text'),
        ),
    ]
