# Generated by Django 3.1.1 on 2020-12-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0029_auto_20201223_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='bonus_link',
            field=models.URLField(blank=True, null=True, verbose_name='Bonus Link'),
        ),
    ]
