# Generated by Django 3.1.1 on 2021-01-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0030_casino_bonus_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casino',
            options={'ordering': ['-trust_score'], 'verbose_name': 'Casino', 'verbose_name_plural': 'Casinos'},
        ),
        migrations.RemoveField(
            model_name='casino',
            name='review_fi',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='review_sv',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='seo_description_fi',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='seo_description_sv',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='seo_title_fi',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='seo_title_sv',
        ),
        migrations.RemoveField(
            model_name='country',
            name='adj_name_fi',
        ),
        migrations.RemoveField(
            model_name='country',
            name='adj_name_sv',
        ),
        migrations.RemoveField(
            model_name='country',
            name='menu_name_fi',
        ),
        migrations.RemoveField(
            model_name='country',
            name='menu_name_sv',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_fi',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_sv',
        ),
        migrations.RemoveField(
            model_name='country',
            name='seo_description_fi',
        ),
        migrations.RemoveField(
            model_name='country',
            name='seo_description_sv',
        ),
        migrations.RemoveField(
            model_name='country',
            name='seo_title_fi',
        ),
        migrations.RemoveField(
            model_name='country',
            name='seo_title_sv',
        ),
        migrations.RemoveField(
            model_name='country',
            name='text_fi',
        ),
        migrations.RemoveField(
            model_name='country',
            name='text_sv',
        ),
        migrations.RemoveField(
            model_name='country',
            name='top_text_fi',
        ),
        migrations.RemoveField(
            model_name='country',
            name='top_text_sv',
        ),
        migrations.RemoveField(
            model_name='games',
            name='name_fi',
        ),
        migrations.RemoveField(
            model_name='games',
            name='name_sv',
        ),
        migrations.RemoveField(
            model_name='games',
            name='seo_description_fi',
        ),
        migrations.RemoveField(
            model_name='games',
            name='seo_description_sv',
        ),
        migrations.RemoveField(
            model_name='games',
            name='seo_title_fi',
        ),
        migrations.RemoveField(
            model_name='games',
            name='seo_title_sv',
        ),
        migrations.AlterField(
            model_name='casino',
            name='support_score',
            field=models.CharField(choices=[('50', '5.0'), ('49', '4.9'), ('48', '4.8'), ('47', '4.7'), ('46', '4.6'), ('45', '4.5'), ('44', '4.4'), ('43', '4.3'), ('42', '4.2'), ('41', '4.1'), ('40', '4.0'), ('35', '3.5'), ('30', '3.0'), ('25', '2.5'), ('20', '2.0'), ('15', '1.5'), ('10', '1.0'), ('0', '0.0')], max_length=3, verbose_name='Payment & Withdraw Score'),
        ),
    ]
